import Axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import {TextField} from '@material-ui/core';
import styles from '../styles/Home.module.css'
import Link from "next/link";

import { Button } from '@material-ui/core';

// import socketIOClient from "socket.io-client"; // 소켓 io

// const ENDPOINT = "http://3.6.177.242:3001"; // 소켓 io 포트랑 연결


import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
  useQuery,
  gql
} from "@apollo/client";  // apollo 이용을 위한 것들



export default function Home({launches}) {
  
  
  useEffect(() => {
  }, []);

  return (
   <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Link href='/view/Signin' as={`/view/Signin`} >
        <a>
          <Button variant="contained" color="primary">
            Signin
          </Button>
        </a>
      </Link>
      
      <Link href='/view/SignupConfirm' as={`/view/SignupConfirm`} >
        <a>
          <Button variant="contained" color="primary">
            Signup
          </Button>
        </a>
      </Link>
      
      <Link href='/view/Main' as={`/view/Main`} >
        <a>
          <Button variant="contained" color="primary">
            Main
          </Button>
        </a>
      </Link>
    </div>
    );
}

//------------------------------graphql 서버 렌더링
// const Query = gql`
// query{
//   modelQuery(Query : "find", Collection : "Company", Data : {CEON : "변무영"})
//   {
//     CEON
//   }
// }
// `

// export async function getStaticProps(context) { // 서버 렌더링
  
//   const client = new ApolloClient({ // apollo 포트로 데이터 전송할 client 생성
//     uri : 'http://localhost:4000',
//     cache : new InMemoryCache()
//   })
  
//   const {data} = await client.query({ // apollo로 데이터 전송
//     query : Query
//   }) 
  
  
//   return {
    
//     props : {
//       launches : JSON.stringify(data.modelQuery) // 위에 Myapp으로 보낼 apollo 결과값들
      
//     }
//   }
// } 