import Axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import {TextField} from '@material-ui/core';
import styles from '../styles/Home.module.css'
import Link from "next/link";
import { useRouter } from "next/router";

import { Button } from '@material-ui/core';

import { useCookies } from "react-cookie";

export default function Home({launches}) {
  const router = useRouter();

  // useEffect(()=> { // 쿠키가 있을경우 메인화면으로
  //   if(cookies.isLogined){
  //     router.push('/view/Main');
  //   }
  // },[])
  
  const [password,setPassword] = useState('');
  const [cookies, setCookie, removeCookie] = useCookies(['isLogined'])

  function passwordHandler(e) {
    setPassword(e.target.value)
  }

  function login(e) {
    e.preventDefault();
    Axios.get('http://'+process.env.NEXT_PUBLIC_IP+':'+process.env.NEXT_PUBLIC_React_Port+'/api/login',{params :{password : password}})
    .then((result) => {
      console.log(result)
      if(result.data.result === true) {
        
        alert('로그인 성공, 30분동안 bcrypt로 암호화된 비밀번호가 쿠키에 저장됩니다.');
        setCookie('isLogined',result.data.BPW,{path: '/', expires: new Date(Date.now()+1800000)});
        router.push('/view/Main')
      }
      else {
        alert('비밀번호가 다릅니다')
      }
    })
  }
  return (
   <div className={styles.container}>
      <Head>
        <title>gsBlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <form onSubmit={login} >
      <TextField
        name="password"
        label="password"
        type="password"
        autoComplete="password"
        value={password}
        onChange={passwordHandler} />

      <Button
        variant="contained"
        color="primary"
        type="submit">
        Enter
      </Button>
      </form>
    </div>
    );
}


//------------------------------graphql 서버 렌더링
// const Query = gql`
// query{
//   modelQuery(Query : "find", Collection : "Company", Data : {CEON : "변무영"})
//   {
//     CEON
//   }
// }
// `

// export async function getStaticProps(context) { // 서버 렌더링
  
//   const client = new ApolloClient({ // apollo 포트로 데이터 전송할 client 생성
//     uri : 'http://localhost:4000',
//     cache : new InMemoryCache()
//   })
  
//   const {data} = await client.query({ // apollo로 데이터 전송
//     query : Query
//   }) 
  
  
//   return {
    
//     props : {
//       launches : JSON.stringify(data.modelQuery) // 위에 Myapp으로 보낼 apollo 결과값들
      
//     }
//   }
// } 